spring:
  datasource:
    url: jdbc:mysql://localhost:3306/produtosapi?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: testes
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  
    
